#Data Manipulation in Python

**Objectives**
* Learn Colaboratory fundanmental operations
* Learn and Review Python Basics
* Learn Numpy Basics
* Learn Pandas Basics

##Introduction to Colaboratory 
* Install Colaboratory (check *class doc*)
* Install and import python packages
* Load and Save data

In [0]:
#@title import packages
variable_name = ""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from __future__ import division # for python2, python 2 default integer division

import warnings
warnings.filterwarnings('ignore')

In [93]:
#@title install packages
!pip install pandasql

## Python Basics

**Numeric Types**


In [94]:
x = 2

# Use type() to check the variable type
print(type(x)) # class 'int'

x = x ** 3
print(x) # 4; exponential

x += 1 # addiction
print(x)

y = 1.5
print(type(y)) # class 'float'

x += y
print(type(x)) # class 'float'


<class 'int'>
8
9
<class 'float'>
<class 'float'>


**Boolean**

In [95]:
t = True
f = False

print(type(t)) # class 'bool' 
print(t or f) # True
print(t and f) # False 
print(not t) # False
print(not f) # True


print(1 or f) # (Advanced, just know it is enough)


<class 'bool'>
True
False
False
True
1


**String**

Strings are immutable type

In [96]:
s1 = 'single quote' # use single quotes
print(type(s1)) # class 'str'

s2= "double quote" # use double quotes 
print(type(s2)) # class 'str'

x = 100
s3 = s1 + ' huozhe ' + s2 + str(x) # string concatenation
print(s3)

print('TEXT: ' + s3)
print('Caplitalize the string: ' + s3.capitalize()) # Caplitalize the string 
print('Uppercase the string: ' + s3.upper()) # Uppercase the string
print('\'o\' occurrences: ' + str(s3.count('o'))) # Count the occurrences of a character
print('first \'te\' index: ' + str(s3.index('te'))) # The lowest index of the occurrence 
print(s3[0]) # string indexing

s4 = '{0} huozhe {1} {2}'.format(s1, s2, 100) # (Advanced)
print(s4)

<class 'str'>
<class 'str'>
single quote huozhe double quote100
TEXT: single quote huozhe double quote100
Caplitalize the string: Single quote huozhe double quote100
Uppercase the string: SINGLE QUOTE HUOZHE DOUBLE QUOTE100
'o' occurrences: 4
first 'te' index: 10
s
single quote huozhe double quote 100


In [97]:
# (Advanced)Tripe Quotes
s = '''
You can specify multi-line string.
This is an example.
'''

print(s)


You can specify multi-line string.
This is an example.



####Lists

Lists are mutable type


In [98]:
lst1 = [] # initialize an empty list
print(type(lst1)) # class 'List'

lst2 = [1, 2, 3, 4] # create a list with same data type values
print(lst2)

lst3 = ['one', 2, 'three', 4] # create a list with different data type values
print(lst3)


<class 'list'>
[1, 2, 3, 4]
['one', 2, 'three', 4]


In [99]:
lst2.append(5) # append a new element to end of the list
print(lst2)

lst2.pop(3) # remove the last element fo the list
print(lst2)

lst2[2] = 100 # list is mutable
print(lst2)

[1, 2, 3, 4, 5]
[1, 2, 3, 5]
[1, 2, 100, 5]


In [100]:
print(lst2[0]) # list indexing
print(lst2[-1]) # negative index, access from end of list
print(len(lst2)) # the length of list
print(lst2 + lst3) # list concatenation

1
5
4
[1, 2, 100, 5, 'one', 2, 'three', 4]


In [101]:
# (Advanced)lst3 = lst2[:] 
# By using this way, lst3 is a deep copy of lst2
# When changing one of the value of lst3, the lst2 will not be changed
lst3 = lst2[:] # copy
lst3[0] = 'lst3'

lst4 = lst2.copy() # copy
lst4[0] = 'lst4'

lst5 = lst2 # reference
lst5[0] = 'lst2'


print(lst3)
print(lst2)
print(lst4)
print('\n')

lst2[0] = ['this', 'is', 'nested', 'list'] # put a list into a list
print(lst2) # original list
print('\n')

# (Advanced+) shallow copy vs deep copy
lst6 = lst2[:]
lst6[0][2] = 'magic'
print('Shallow Copy original list: ')
print(lst2) # original list
print(lst6)
print('\n')

import copy
lst2[0] = ['this', 'is', 'nested', 'list'] # put a list into a list
lst6 = copy.deepcopy(lst2)
lst6[0][2] = 'magic'
print('Deep Copy original copy:')
print('lst2: ' + str(lst2)) # original list
print('lst6: ' + str(lst6)) 

['lst3', 2, 100, 5]
['lst2', 2, 100, 5]
['lst4', 2, 100, 5]


[['this', 'is', 'nested', 'list'], 2, 100, 5]


Shallow Copy original list: 
[['this', 'is', 'magic', 'list'], 2, 100, 5]
[['this', 'is', 'magic', 'list'], 2, 100, 5]


Deep Copy original copy:
lst2: [['this', 'is', 'nested', 'list'], 2, 100, 5]
lst6: [['this', 'is', 'magic', 'list'], 2, 100, 5]


In [102]:
a = [1, 22]
b = a[:]
b[0] = 3

print(a)

[1, 22]


**Slicing**

In [103]:
lst = range(6) # create an list of numbers using built-in function range
print(type(lst)) # class 'range'

lst = list(lst) # change to list
print(type(lst)) # class 'list'

# [start(inclusive) : end(exclusive) : step]
print(lst) # [0, 1, 2, 3, 4, 5]
print(lst[0:6]) # index from 0 to 5, [0, 1, 2, 3, 4, 5]
print(lst[1:]) # index from 1 to the end, [1, 2, 3, 4, 5]
print(lst[:4]) # index from start to 4, [0, 1, 2, 3]
print(lst[:]) # the whole list, [0, 1, 2, 3, 4, 5]
print(lst[:-1]) # negative index slicing, [0, 1, 2, 3, 4]
print(lst[-1:]) # negative index slicing, [5]
print(lst[::2]) # change index step to 2, [0, 2, 4]
print(lst[::-1]) # reverse order, [5, 4, 3, 2, 1, 0], common usage

lst[2:4] = [3, 2] # modify the values by slicing
print(lst) # [0, 1, 3, 2, 4, 5]

<class 'range'>
<class 'list'>
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4]
[5]
[0, 2, 4]
[5, 4, 3, 2, 1, 0]
[0, 1, 3, 2, 4, 5]


In [104]:
print(lst)
print(lst[0:6:2]) 

[0, 1, 3, 2, 4, 5]
[0, 3, 4]


In [105]:
ss = 'Hello World!' # initialize a string
print(ss)

print(ss[:]) # the whole list
print(ss[1:3]) # index from 1 to 2

Hello World!
Hello World!
el


**Looping**

In [106]:
# basic loop
skills = ['ML', 'Stat', 'Coding', 'Business']
for skill in skills:
  print(skill)

ML
Stat
Coding
Business


In [107]:
# enumerate, bind index with list element
# [(0, 'ML'), (1, 'Stat')..]
skills = ['ML', 'Stat', 'Coding', 'Business']
for idx, skill in enumerate(skills):
  print('{idx_} : {skill_}'.format(skill_ = skill, idx_ = idx))

0 : ML
1 : Stat
2 : Coding
3 : Business


In [108]:
# list comprehension
nums = list(range(6))
print(nums)

lst = [x ** 2 for x in nums]
print(lst)

# same as list comprehension
lst_temp = []
for x in nums:
  lst_temp.append(x ** 2)
print(lst_temp)

[0, 1, 2, 3, 4, 5]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25]


# **Dictionary**

{key: value} 

key-value pairs

In [109]:
skills = ['ML', 'Stat', 'Coding', 'Business']
scores = [90, 80, 1, 59]

print(scores[skills.index('Coding')])

score_dict = {'ML': 90, 'Stat': 80, 'Coding': 1, 'Business': 59} # create a dictionary
print(score_dict['ML']) # get ML score
print('Stat' in score_dict) # check if 'Stat' in the dictionary

score_dict['Spark'] = 70 # Add a new key-value pair to the dictionary
print(score_dict['Spark'])

print("current score: %d" % score_dict['Coding'])
score_dict['Coding'] = 100 # Modify the existing value in the dictionary
print("afterwards: " + str(score_dict['Coding']))

score_dict.pop('Spark')

1
90
True
70
current score: 1
afterwards: 100


70

In [110]:
# dictionary comprehension
num_dict={x: x**2 if x % 2 == 0 else x for x in range(6)} # create dictionary

# for x in range(6):
#   if x%2 == 0:
#     x ** 2
#   else:
#     x

print(num_dict)
print(num_dict[4])

{0: 0, 1: 1, 2: 4, 3: 3, 4: 16, 5: 5}
16


In [111]:
# loop over dictionary
for skill in score_dict.values():
  print(skill)
  
#   score = score_dict[skill]
#   print("{} : {}".format(skill, score))

90
80
100
59


**Set**

A set is an unordered collection of *distinct* elements. 

In [112]:
skills = {'ML', 'Stat', 'Coding', 'Business'}
skills_list = ['ML', 'Stat', 'Coding', 'Business']



print('Business' in skills) # check if an element is in a set
print('Spark' in skills) # False

skills.add('Spark') # add an element
print(skills)
skills.remove('Spark') # remove an element
print(skills)

# loop over a set
for idx, skill in enumerate(skills):
  print(f"{skill} : {idx}")

# set comprehension
nums = {num for num in range(6)}
print(type(nums)) # class 'set'

print(skills)

True
False
{'ML', 'Stat', 'Coding', 'Spark', 'Business'}
{'ML', 'Stat', 'Coding', 'Business'}
ML : 0
Stat : 1
Coding : 2
Business : 3
<class 'set'>
{'ML', 'Stat', 'Coding', 'Business'}


**Tuple**

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [113]:
t = (21, 42) # create a tuple
print(type(t))

skills = ['ML', 'Stat', 'Coding', 'Business']
t_dict = {('Laidata', idx) : skill for idx, skill in enumerate(skills)} # create a dictionary with tuple keys
print(t_dict)


<class 'tuple'>
{('Laidata', 0): 'ML', ('Laidata', 1): 'Stat', ('Laidata', 2): 'Coding', ('Laidata', 3): 'Business'}


##Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. 


**Arrays**

In [114]:
lst = [[1, 2, 3], [4, 5, 6]] # 2x3
a = np.array(lst) # create array from lists
print(type(a)) # class 'numpy.ndarray'
print(a)
print(a[0]) # first row
print(a[0][1]) # first row, second column
print(a.shape) # 2 x 3
print(a.ndim) # 2 dimensions
print(a.dtype) # data type of the elements of array
print(a.size) # total number of elements in the matrix


<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[1 2 3]
2
(2, 3)
2
int64
6


In [115]:
b = np.arange(0, 10, 2, dtype='float') # create 1d array, [start, stop)
print(type(b)) # class 'numpy.ndarray'
print(b)
print(b.shape)

c = np.linspace(1.5, 2.5, 9) # create 1d array with float, [start, stop]
print(type(c)) # class 'numpy.ndarray'
print(c)
print(c.shape)

d = np.zeros((2, 3)) # all zeros
print(type(d)) # class 'numpy.ndarray'
print(d)

e = np.ones((2, 3)) # all ones
print(type(e)) # class 'numpy.ndarray'
print(e)

f = np.full((2, 3), 9) # constant matrix
print(type(f)) # class 'numpy.ndarray'
print(f)

g = np.eye(3) # 3 x 3 identity matrix
print(type(g)) # class 'numpy.ndarray'
print(g)

<class 'numpy.ndarray'>
[0. 2. 4. 6. 8.]
(5,)
<class 'numpy.ndarray'>
[1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5  ]
(9,)
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
[[9 9 9]
 [9 9 9]]
<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [116]:
h = b.reshape(5, 1)
print(h.shape)

i = c.reshape(-1, 1)
print(i)
print(i.shape)

j = d.reshape((2, 3, 1))
print(j)
print(j.shape)

# (Advanced)show all the values
# np.set_printoptions(threshold = np.nan) 
print(np.arange(10000).reshape((100, 100)))


(5, 1)
[[1.5  ]
 [1.625]
 [1.75 ]
 [1.875]
 [2.   ]
 [2.125]
 [2.25 ]
 [2.375]
 [2.5  ]]
(9, 1)
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
(2, 3, 1)
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


**Indexing and Slicing**

In [117]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
print(a[1]) # access a row
print(a[:, 1]) # access a col
print(a[1, 1]) # access single value

[[2 3]
 [6 7]]
[5 6 7 8]
[ 2  6 10]
6


In [118]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# (Advanced)Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
r1 = a[0, :] # rank 1 view of the first row
r2 = a[0:1, :] # rank 2 view of the first row 
print(r1, r1.shape)
print(r2, r2.shape)

r1 = r1.reshape(-1, r1.shape[0])
print(r1, r1.shape)

[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[[1 2 3 4]] (1, 4)


In [119]:
# boolean masking
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a_idx1 = (a < 5) # return the boolean array that satisfies the conidtion
print(a_idx1)
a_idx2 = (a >=5) & (a <= 10) # return the boolean array that satisfies the conidtion
print(a_idx2)

print(a[a_idx1]) # return the corresponding array
print(a[a_idx2]) # return the corresponding array

print(a[(a > 5) & (a < 10)]) # single statement


[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
[1 2 3 4]
[ 5  6  7  8  9 10]
[6 7 8 9]


**Math**

In [120]:
import numpy as np

a = np.array([[10, 11, 12], [13, 14, 15]])
print(a.shape)
print(a)
b = np.arange(1, 7).reshape((2, 3))
print(b.shape)
print(b)

# element-wise calculation:
print(a + b)
print(a - b)
print(np.add(a, b))
print(a * b)

# Matrix product
print(np.dot(a, b.transpose())) # 2x3, 3x2
print(a.T.dot(b)) # 3x2, 2x3

# calculation along row or column index, calculate by the index of the axis which is set
print(np.sum(a, axis = 0)) # sum along row
print(np.sum(a, axis = 1)) # sum along column


(2, 3)
[[10 11 12]
 [13 14 15]]
(2, 3)
[[1 2 3]
 [4 5 6]]
[[11 13 15]
 [17 19 21]]
[[9 9 9]
 [9 9 9]]
[[11 13 15]
 [17 19 21]]
[[10 22 36]
 [52 70 90]]
[[ 68 167]
 [ 86 212]]
[[ 62  85 108]
 [ 67  92 117]
 [ 72  99 126]]
[23 25 27]
[33 42]


In [121]:
print(a, a.shape)
print(b, b.shape)
# print(a + b)
# print(a - b)
# print(np.add(a, b))
# 2x3 * 3x2 -> 2x2
# 3x2 * 2x3 -> 3x3
print(b.T, b.T.shape)

a.T.dot(b)


[[10 11 12]
 [13 14 15]] (2, 3)
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


array([[ 62,  85, 108],
       [ 67,  92, 117],
       [ 72,  99, 126]])

In [122]:
# (Advanced+)broadcasting


import numpy as np

a = np.array([[10, 11, 12], [13, 14, 15]])
print(a)

a += 1 # add 1 to all the elements
print(a)

a += np.array([-1, -2, -3]) # add [-1, -2, -3] to all columns for each row
print(a)

a += np.array([[-1], [-2]]) # add [[-1], [-2]] to all rows for each column
print(a)

[[10 11 12]
 [13 14 15]]
[[11 12 13]
 [14 15 16]]
[[10 10 10]
 [13 13 13]]
[[ 9  9  9]
 [11 11 11]]


Read more for [broadcasting](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)

In [123]:
import numpy as np

# Two dimensions are compatible when
# they are equal, or
# one of them is 1
a = np.array([1, 2, 3]) # 1x3
b = np.array([[4], [5], [6]]) # 3x1

print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


**Random**

In [124]:
np.random.seed(42) # same seed can repro the same scenario so it is deterministic

print(np.random.rand(2,2)) # Random numbers between [0,1) of shape 2,2
print(np.random.randn(2,2)) # Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randint(0, 10, size=[2,2])) # Random integers between [0, 10) of shape 2,2
print(np.random.random()) # One random number between [0,1)
print(np.random.random(size=[2,2])) # Random numbers between [0,1) of shape 2,2
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10)) # Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1])) # Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(np.arange(100),size=[10,3],replace=True)) # get 10x3 random samples from [0-99] with replacement 

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
[[-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]]
[[5 4]
 [1 7]]
0.8324426408004217
[[0.21233911 0.18182497]
 [0.18340451 0.30424224]]
['u' 'o' 'a' 'a' 'i' 'i' 'e' 'o' 'o' 'i']
['e' 'u' 'i' 'o' 'o' 'i' 'a' 'u' 'o' 'e']
[[89 52  1]
 [83 91 59]
 [70 43  7]
 [46 34 77]
 [80 35 49]
 [ 3  1  5]
 [53  3 53]
 [92 62 17]
 [89 43 33]
 [73 61 99]]


In [125]:
#(Advanced) use random generator to do train/test split

url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/d546eaee765268bf2f487608c537c05e22e4b221/iris.csv"
iris = pd.read_csv(url)
print(iris.head())
print(iris.info())

# Split data into training and testing
np.random.seed(42)
iris_idx = np.arange(iris.shape[0])

num_training = int(np.floor(0.75 * iris.shape[0]))
iris_train_idx = np.random.choice(iris_idx, size=num_training, replace=False)
iris_test_idx = np.delete(iris_idx, iris_train_idx)
iris_train = iris.iloc[iris_train_idx]
iris_test = iris.iloc[iris_test_idx]

print(iris_train.info())
print(iris_test.info())


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 112 entries, 73 to 126
Data columns (total 5 columns):
sepal_length    112 non-null float64
sepal_width     112 non-null float64
petal_length    112 non-null float64
petal_width     112 non-null float64
species         11

In [126]:
# (Advanced)use np.random.shuffle
iris_idx = np.arange(iris.shape[0])
np.random.shuffle(iris_idx)
iris.index = iris_idx
num_training = int(np.floor(0.75 * iris.shape[0]))
iris_train = iris.iloc[:num_training]
iris_test = iris.iloc[num_training:]

print(iris_train.info())
print(iris_test.info())


<class 'pandas.core.frame.DataFrame'>
Int64Index: 112 entries, 84 to 105
Data columns (total 5 columns):
sepal_length    112 non-null float64
sepal_width     112 non-null float64
petal_length    112 non-null float64
petal_width     112 non-null float64
species         112 non-null object
dtypes: float64(4), object(1)
memory usage: 5.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 38 entries, 50 to 142
Data columns (total 5 columns):
sepal_length    38 non-null float64
sepal_width     38 non-null float64
petal_length    38 non-null float64
petal_width     38 non-null float64
species         38 non-null object
dtypes: float64(4), object(1)
memory usage: 1.8+ KB
None


In [127]:
# (Advanced)use sklearn to spilt data
from sklearn.model_selection import train_test_split

X = iris.drop('species', axis = 1)
y = iris['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=21, stratify=y)

print(X_train.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112 entries, 16 to 148
Data columns (total 4 columns):
sepal_length    112 non-null float64
sepal_width     112 non-null float64
petal_length    112 non-null float64
petal_width     112 non-null float64
dtypes: float64(4)
memory usage: 4.4 KB
None


AttributeError: ignored

##Pandas

**pandas** is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python. Additionally, it has the broader goal of becoming **the most powerful and flexible open source data analysis / manipulation tool available in any language**. It is already well on its way toward this goal.

The two primary data structures of pandas, **Series (1-dimensional)** and **DataFrame (2-dimensional)**, handle the vast majority of typical use cases in finance, statistics, social science, and many areas of engineering. pandas is built on top of **NumPy** and is intended to integrate well within a scientific computing environment with many other 3rd party libraries.

**Load Data**

In [0]:
import pandas as pd
# read data from csv file
# pd.read_csv("../data_folder/data.csv")

In [0]:
# read data from URL
iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df_iris = pd.read_csv(iris, sep=',', header=None)
print(df_iris.head())

In [0]:
# read data from github link
import pandas as pd
import io
import requests
url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/d546eaee765268bf2f487608c537c05e22e4b221/iris.csv"
c=pd.read_csv(url)


In [0]:
c.head()

In [0]:
c.tail()

In [0]:
# Read data from Google Drive (not recommended)
# https://colab.sandbox.google.com/notebooks/io.ipynb

In [0]:
# Read data from Google Drive (recommend)
# step 1: change your csv file in Drive as Anyone with the link can view
# https://drive.google.com/open?id=1k0ZYUdqqjPjVWCw3ElcaMMRFg6H3-Pjh
# https://drive.google.com/open?id=1Cv7_0sRGwwaKjd0PuquybacS6DA8PU4B
file_id='1k0ZYUdqqjPjVWCw3ElcaMMRFg6H3-Pjh'
link='https://drive.google.com/uc?export=download&id={FILE_ID}'
csv_url=link.format(FILE_ID=file_id)
df_uk_rain = pd.read_csv(csv_url)
print(df_uk_rain.columns)
df_uk_rain.columns = ['water_year','rain_octsep', 'outflow_octsep',
              'rain_decfeb', 'outflow_decfeb', 'rain_junaug', 'outflow_junaug']

df_uk_rain.head(10)

In [0]:
# Save dataframe to CSV and save to local machine
df_uk_rain.to_csv('df.csv', index=False)
from google.colab import files
# files.download('df.csv')

**Data Structure**

**Series** is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index.

**DataFrame** is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object. 

In [0]:
# Series from list
s = pd.Series([1,3,5,np.nan,6,8], index = ['a','b','c','d','e','f'])

print(s)
print(type(s))

s.index


In [0]:
# Dataframe from lists
df = pd.DataFrame({'list_x': [1,2,3,4,5,6],'list_y': ['1', '2', '3', '4', '5', '6'], 'list_z': ['1',2,3,4,5,6]})
print(df)
df.info()

In [0]:
# Dataframe first 5(default) rows
print(df_iris.head())
print(df_iris.tail())

In [0]:
# Dataframe information
df_iris.info()

In [0]:
# Dataframe stats information
df_iris.describe()

In [0]:
# column data type
df_iris.dtypes

In [0]:
# index info
df_iris.index

In [0]:
# change column names
attributes = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
df_iris.columns = attributes

df_iris.head(1)

**Indexing and Slicing**

In [0]:
# use [] square brackets, only columns
df1 = df_iris['sepal_length']
print(df1.head())
print(type(df1))

df2 = df_iris[['sepal_length']]
print(df2.head())
print(type(df2))

df3 = df_iris[['sepal_length', 'petal_length']]
print(df3.head())
print(type(df3))

df4 = df_iris[1:3]
print(df4)
print(type(df4))


In [0]:
# selection by position, use iloc, endpoint is excluded
df1 = df_iris.iloc[[3]]
print(df1)
print(type(df1))

df2 = df_iris.iloc[3:5,0:2]
print(df2)
print(type(df2))

df3 = df_iris.iloc[[1,2,4],[0,2]]
print(df3)
print(type(df3))


In [0]:
# selection by lable, use loc , endpoint is included
df1 = df_iris.loc[:, 'sepal_length']
print(df1.head())
print(type(df1))

df2 = df_iris.loc[1:3, ['sepal_length']]
print(df2.head())
print(type(df2))

df3 = df_iris.loc[[1, 3], ['sepal_length', 'petal_length']]
print(df3)

In [0]:
# boolean indexing
df1 = df_iris[(df_iris['sepal_length'] > 6.0) & (df_iris.petal_length < 5.0)]
#print(df1)

df2 = df_iris.loc[(df_iris['sepal_length'] > 6.0) & (df_iris.petal_length < 5.0), ['sepal_width', 'petal_width']]
df2 = df2.reset_index()
print(df2)
df2.index

**Useful functions**

apply, applymap, (lambda)

In [0]:
# Applying a function on 1D arrays to each column or row. 
# DataFrame’s apply method does exactly this
# DataFrame.apply

import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=['a','b','c'], index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df)

def func(col):
  return col.max() - col.min()

# use lambda function
print('haluo')
print(df.apply(lambda x: x.mean(), axis='index'))

print('haluo2:')
print(df.apply(lambda x: x.mean(), axis='columns'))


# add a new column
df['range'] = df[['a','b','c']].apply(func, axis='columns')
print(df)

# for some columns
df[['a', 'b']].apply(sum, axis=0)



In [0]:
# Many of the most common array statistics (like sum and mean) are DataFrame methods, so using apply is not necessary.
# Element-wise Python functions can be used, too. 
# Suppose you wanted to compute a formatted string from each floating point value in frame. 
# You can do this with applymap
# DataFrame.applymap

df = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list('abc'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df.applymap(lambda x: x**2))

In [0]:
# Get the starting year and change it to datetime type
def base_year(year):
    base_year = year[:4]
    base_year= pd.to_datetime(base_year).year
    return base_year

df_uk_rain['year'] = df_uk_rain.water_year.apply(base_year)
df_uk_rain.head(5)

# **Merging**

Read this [document](https://pandas.pydata.org/pandas-docs/stable/merging.html) for more info


In [0]:
# two dataframe join or concatenate
df_right=pd.DataFrame({'year':np.arange(1980,1990),'rain_cn':np.arange(800,810)})
print(df_right)
df_right2=pd.DataFrame({'year': [900], 'rain_cn': [1800]})
print(df_right2)
df_right=pd.concat([df_right, df_right2])
print(df_right)


In [0]:
# SQL like inner join:
df_join=pd.merge(df_uk_rain, df_right, left_on='year',right_on='year',how='inner')
print(df_join)

In [0]:
# SQL like left join
df_left_join=pd.merge(df_uk_rain, df_right, left_on='year',right_on='year', how='left') # left_on, right_on
df_left_join.head()

In [0]:
from pandasql import sqldf

def pysqldf(q):
  return sqldf(q, globals())

q = '''
SELECT * 
FROM df_uk_rain a LEFT JOIN df_right b
ON a.year = b.year
LIMIT 5
'''

pysqldf(q)


**Grouping**

Read this [document](https://pandas.pydata.org/pandas-docs/stable/groupby.html) for more info

In [0]:
# groupby: similar to SQL groupby
df_uk_rain.groupby(df_uk_rain['year'] // 10 *10)['rain_octsep','outflow_octsep','rain_decfeb'].max()

In [0]:
# groupby multiple columns
df_uk_rain.groupby([df_uk_rain.year // 10 * 10, df_uk_rain['rain_octsep'] // 1000 * 1000], as_index=True)[['outflow_octsep','outflow_decfeb', 'outflow_junaug'] ].mean()

In [0]:
# groupby + apply + lambda
df_uk_rain.groupby(df_uk_rain.year // 10 *10)['rain_octsep','outflow_octsep','rain_decfeb'].apply(lambda x: np.max(x, axis=0)).reset_index() # same result as first groupby example except index

**Data Preprocessing**


*   Duplication
*   Outlier
*   Missing Value



In [0]:
#@title Duplication

In [0]:
df_uk_rain

In [0]:
# check if a column has duplicates
df_uk_rain.iloc[np.where(df_uk_rain[['water_year', 'rain_octsep']].duplicated())]

In [0]:
np.where(df_uk_rain.rain_octsep.duplicated())

In [0]:
# create a duplicated row as the last row
df_dup=df_uk_rain
df_dup.loc[len(df_dup)]=df_dup.iloc[0]
df_dup.iloc[[0,-1]] # first and last row

In [0]:
# check duplicate rows
df_dup.duplicated()

In [0]:
# remove duplicates
df_dedup=df_dup.drop_duplicates()
df_dedup.iloc[[0,-1],:]

In [0]:
#@title Outlier

# boxplot, winsorizing

![alt text](https://www.mathsisfun.com/data/images/outlier.svg)<br>
![alt text](https://statistics.laerd.com/statistical-guides/img/pearson-6.png)

In [0]:
import seaborn as sns
# Simulate data
dt_outlier=np.concatenate([np.random.normal(0,1,1000),np.random.normal(8,1,10)])
sns.set_style('whitegrid')
sns.distplot(dt_outlier)

Outlier Detection： Boxplot  <br>
Interquartile Range(IQR):
IQR= Upper Quantile(Q3) - Lower Quartile(Q1) <br>
Lower Limit = Q1 - 1.5 IQR <br>
Upper Limit = Q3 + 1.5 IQR <br>
![alt text](https://i.stack.imgur.com/mpbTr.gif)


In [0]:
sns.boxplot(dt_outlier,orient='v')

In [0]:
# define a function remove outlier using IQR
def iqr_outlier_rm(dt_input):
  lq,uq=np.percentile(dt_input,[25,75])
  lower_l=lq - 1.5*(uq-lq)
  upper_l=uq + 1.5*(uq-lq)
  return dt_input[(dt_input >=lower_l)&(dt_input<=upper_l)]
  
dt_outlier_ws=iqr_outlier_rm(dt_outlier)
sns.boxplot(dt_outlier_ws,orient='v')

In [0]:
#@title Missing value

In [0]:
# check rows: return rows have NaN
idx_row_nan=pd.isnull(df_left_join).any(axis=1) # return bool value
df_left_join.loc[idx_row_nan].head()

In [0]:
# check cols
pd.isnull(df_left_join).any(axis=0)

In [0]:
# select the rows without NaN
df_left_join.loc[-idx_row_nan] # negative bool can be used

In [0]:
# check nan rows
df_left_join.loc[idx_row_nan]

In [0]:
# Imputation: replace NaN with 0
df_left_join_1=df_left_join
df_left_join_1.fillna(0).tail(5)

In [0]:
# drop NaN rows
df_left_join_0=df_left_join
df_left_join_0.dropna(axis='index') # axis = 0 or 1 is deprecated for dropna command

In [0]:
# Replace the NaN with column mean
df_left_join_1=df_left_join.copy()
print(df_left_join_1['rain_cn'].mean())
df_left_join_1.tail(5)
df_left_join_1['rain_cn'].fillna(df_left_join_1['rain_cn'].mean(), inplace=True)
df_left_join_1.tail(5)
