<a href="https://colab.research.google.com/github/IggyZhao/Python-Skills-by-Iggy/blob/master/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [ ]:
# from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[1.4957e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4364, 0.8132, 0.7446],
        [0.8434, 0.7347, 0.8137],
        [0.2535, 0.7648, 0.8982],
        [0.0692, 0.9628, 0.5932],
        [0.1019, 0.5564, 0.1851]])


Construct a matrix filled zeros and of dtype long:



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.4512,  1.3296, -1.3831],
        [-1.3034, -1.5074, -3.8710],
        [-2.3458, -0.4338, -0.6906],
        [ 0.9410,  0.3552, -0.8260],
        [ 1.5713, -0.9252, -1.0299]])


Get its size:



In [ ]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.0465,  1.4243, -0.7216],
        [-1.1133, -1.0709, -3.8253],
        [-1.3888,  0.5210, -0.4203],
        [ 1.6822,  0.3758, -0.0704],
        [ 2.5105, -0.2335, -0.9774]])


Addition: syntax 2



In [ ]:
print(torch.add(x, y))

tensor([[-1.0465,  1.4243, -0.7216],
        [-1.1133, -1.0709, -3.8253],
        [-1.3888,  0.5210, -0.4203],
        [ 1.6822,  0.3758, -0.0704],
        [ 2.5105, -0.2335, -0.9774]])


Addition: providing an output tensor as argument



In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.0465,  1.4243, -0.7216],
        [-1.1133, -1.0709, -3.8253],
        [-1.3888,  0.5210, -0.4203],
        [ 1.6822,  0.3758, -0.0704],
        [ 2.5105, -0.2335, -0.9774]])


Addition: in-place



In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.0465,  1.4243, -0.7216],
        [-1.1133, -1.0709, -3.8253],
        [-1.3888,  0.5210, -0.4203],
        [ 1.6822,  0.3758, -0.0704],
        [ 2.5105, -0.2335, -0.9774]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [ ]:
print(x[:, 1])

tensor([ 1.3296, -1.5074, -0.4338,  0.3552, -0.9252])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6602])
-0.6601998209953308


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)




CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.3398], device='cuda:0')
tensor([0.3398], dtype=torch.float64)


In [ ]:
import torch

In [ ]:
x = torch.tensor([[1,2,3]])
y = torch.tensor([[2,2,2]])
print(x.shape) # Prints torch.Size([1, 3]), x is a row vector
print(y.shape) # Prints torch.Size([1, 3]), y is a row vector
print(torch.stack([x, y]).shape) # prints torch.Size([2, 1, 3])
print(torch.cat([x,y]).shape) 

torch.Size([1, 3])
torch.Size([1, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3])


In [ ]:
torch.stack([x, y])

tensor([[[1, 2, 3]],

        [[2, 2, 2]]])